### ISSUE TITLE
[eval] gemma-4 init fails: 'list' object has no attribute 'keys'

### ISSUE THREAD

**Issue by penfever** [marin-community/evalchemy#139]
Every eval task against a served google/gemma-4-26B-A4B-it checkpoint fails during client-side model initialization; the server loads the checkpoint and would answer requests.

Reproduce:
1. Serve `google/gemma-4-26B-A4B-it` (vLLM loads it).
2. Run any eval task against the endpoint with the pinned client stack.

Failed to initialize model: 'list' object has no attribute 'keys'

Expected: the client initializes gemma-4's config/tokenizer/chat template and the eval runs.

The failure lands after task dataset generation and before any inference request, so it is in the client's model/tokenizer init path, which does not expect a list where the pinned loader reads a mapping. All 13 eval tasks in eval-20260917-134809-google-gemma-4-26B-A4B-it-0b47 fail this way at pin 412ae9c2.
